# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
    Major: 2
    Minor: 4

name: $(Major).$(Minor)$(Rev:.r)

trigger:
- master
- dev

pool: CodeWayAWSLinux

steps:
- script: |
    echo "Testing ...."
    ls -saltr
    python -m build package/
    ls -saltr
    pwd
    ls
    #python3 -m venv venv
    #. ./venv/bin/activate
    #python3 -m pip install --upgrade pip
    #pip install -r requirements.txt 
    #python3 manage.py runserver 0.0.0.0:8010
  displayName: 'Building artifacts'
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'sonar'
    scannerMode: 'Other'
- task: SonarQubeAnalyze@5
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      **/*
      !.git/**/*
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1  
  inputs:    
    #    PathtoPublish: '$(Build.ArtifactStagingDirectory)'                  
    targetPath: $(System.DefaultWorkingDirectory)
    #targetPath: package/dist
    ArtifactName: 'Predifix_app'

- task: DownloadPipelineArtifact@2
  inputs:
    artifact: 'Predifix_app'
#change
